localidades_argentinas = [
"Córdoba, Argentina",
"Río Cuarto, Argentina",
"San Francisco, Argentina",
"Villa María, Argentina",
"Alta Gracia, Argentina",
"Jesús María, Argentina",
"La Falda, Argentina",
"Cosquín, Argentina",
"Capilla del Monte, Argentina",
"Villa General Belgrano, Argentina",
"Marcos Juárez, Argentina",
"Bell Ville, Argentina",
"Río Tercero, Argentina",
"Villa Allende, Argentina",
"Unquillo, Argentina",
"Villa Dolores, Argentina",
"Laboulaye, Argentina",
"Deán Funes, Argentina",
"Morteros, Argentina",
"Salta Argentina",
"San Salvador de Jujuy Argentina",
"Cafayate Argentina",
"Rosario de la Frontera Argentina",
"Metán Argentina",
"Tartagal Argentina",
"Orán Argentina",
"San Ramón de la Nueva Orán Argentina",
"Güemes Argentina",
"Joaquín V. González Argentina",
"Santa Fe Argentina",
"Santa Fe Argentina",
"Rafaela Argentina",
"Venado Tuerto Argentina",
"Santo Tomé Argentina",
"Reconquista Argentina",
"Esperanza Argentina",
"Gálvez Argentina",
"Villa Constitución Argentina",
"San Lorenzo Argentina",
"San Juan Argentina",
"Rivadavia, San Juan, Argentina",
"Chimbas Argentina",
"Pocito Argentina",
"Caucete Argentina",
"Santa Lucía Argentina",
"Albardón Argentina",
"Jáchal Argentina",
"25 de Mayo Argentina",
"San Martín Argentina",
"Catamarca Argentina",
"San Fernando del Valle de Catamarca Argentina",
"Andalgalá Argentina",
"Belén Argentina",
"Santa María Argentina",
"Tinogasta Argentina",
"Recreo Argentina",
"Fiambalá Argentina",
"La Puerta Argentina",
"Santa Rosa Argentina",
"Viejo Argentina",
"La Rioja Argentina",
"La Rioja Argentina",
"Chilecito Argentina",
"Aimogasta Argentina",
"Chamical Argentina",
"Chepes Argentina",
"Villa Unión Argentina",
"Anillaco Argentina",
"Sanagasta Argentina",
"Ulapes Argentina",
"Famatina Argentina",
"Chaco Argentina",
"Resistencia Argentina",
"Barranqueras Argentina",
"Fontana Argentina",
"Presidencia Roque Sáenz Peña Argentina",
"Resistencia Argentina",
"Charata Argentina",
"Las Breñas Argentina",
"Machagai Argentina",
"San Martín Argentina",
"General José de San Martín Argentina",
"Corrientes Argentina",
"Corrientes Argentina",
"Goya Argentina",
"Mercedes Argentina",
"Curuzú Cuatiá Argentina",
"Paso de los Libres Argentina",
"Santo Tomé Argentina",
"Monte Caseros Argentina",
"Bella Vista Argentina",
"Ituzaingó Argentina",
"Virasoro Argentina",
"San Miguel de Tucumán Argentina",
"Yerba Buena Argentina",
"Tafí Viejo Argentina",
"Concepción Argentina",
"Banda del Río Salí Argentina",
"Aguilares Argentina",
"Monteros Argentina",
"Famaillá Argentina",
"Tafí del Valle Argentina",
"Alderetes Argentina",
"Neuquén Argentina",
"Cutral Có Argentina",
"Plaza Huincul Argentina",
"Zapala Argentina",
"Centenario Argentina",
"San Martín de los Andes Argentina",
"Rincón de los Sauces Argentina",
"Junín de los Andes Argentina",
"Villa La Angostura Argentina",
"Chos Malal Argentina",
"Paraná Argentina",
"Concordia Argentina",
"Villaguay Argentina",
"Crespo Argentina",
"Federal Argentina",
"Oro Verde Argentina",
"Victoria Argentina",
"Diamante Argentina",
"Formosa Argentina",
"Clorinda Argentina",
"Pirané, Formosa, Argentina",
"Ingeniero Juárez Argentina",
"El Colorado Argentina",
"Laguna Blanca Argentina",
"Villa Allende Argentina",
"Comandante Fontana Argentina",
"Las Lomitas Argentina",
"Villa Escolar Argentina",
"Herradura Argentina",
"San Luis Argentina",
"Villa Mercedes Argentina",
"Merlo Argentina",
"Merlo San Luis Argentina",
"La Toma Argentina",
"Quines Argentina",
"Villa de la Quebrada Argentina",
"Juana Koslay Argentina",
"Santa Rosa de Conlara Argentina",
"Carpintería Argentina",
"Río Negro Argentina",
"Viedma Argentina",
"San Carlos de Bariloche Argentina",
"General Roca Argentina",
"Cipolletti Argentina",
"Villa Regina Argentina",
"Cinco Saltos Argentina",
"Catriel Argentina",
"Ingeniero Jacobacci Argentina",
"Choele Choel Argentina"
]
